# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13276cb2a0361e6a50d197fbbf0c9716d0788f08461067b82a05fab2291e34d901f7dd89739927323e265e7ced8a38c526ff9090a45b9ece274b2ef3718ba032

test:
  secret_key_base: 82933d57198c33e78c3523a689d6680ea50cabc7397fa0e2065c41cfb2cdfc5e08bc377490b3500263fb677d486210516a78f5d441de8190a589505b0ee40147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
